### ISSUE TITLE
[EPIC] Forum app

### ISSUE THREAD

**Issue by pannkotsky** [pannkotsky/groupmate#13]
For 1st phase
- [ ] Create topic model and API #18 
- [ ] Create post model and API #19 
- [ ] Topic page - structure #20 
- [ ] Topic page - markup #21 
- [ ] Topic listing page - structure #22 
- [ ] Topic listing page - markup #23 

In future
- [ ] Use websockets to push new posts to feed #24 
- [ ] Create answer model and API #25 
- [ ] Answers frontend #26 
- [ ] Ability to tag user #27
