### ISSUE TITLE
[EPIC] Users app

### ISSUE THREAD

**Issue by pannkotsky** [pannkotsky/groupmate#6]
- [ ] Allow login via phone number #3 
- [ ] Add group model #14 
- [ ] Add all necessary fields to user model #7
- [ ] User detail page - structure #8 
- [ ] User detail page - markup #9 
- [ ] User listing page - structure #10 
- [ ] User listing page - markup #11 
- [ ] Ability to edit own profile #12
